
import { Item, ItemEffect, ItemPocket } from "@pokecrystal/core/core/enums/item";
import { Item as ItemType, ItemSchema } from "@pokecrystal/core/core/models";

type ItemSeed = {
    name: string;
    asm_name?: string;
    price: number;
    effect: string;
    param: number;
    pocket: ItemPocket;
    description: string;
    held_effect?: string;
    property?: string;
    field_menu?: string;
    battle_menu?: string;
};

const itemData: Record<Item, ItemSeed> = {
    [Item.NONE]: { name: "NONE", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "No effect." },
    [Item.MASTER_BALL]: { name: "MASTER BALL", price: 0, effect: ItemEffect.POKE_BALL, param: 255, pocket: ItemPocket.BALL, description: "The best BALL that catches a POKéMON without fail." },
    [Item.ULTRA_BALL]: { name: "ULTRA BALL", price: 1200, effect: ItemEffect.POKE_BALL, param: 200, pocket: ItemPocket.BALL, description: "A BALL with a high rate of success." },
    [Item.GREAT_BALL]: { name: "GREAT BALL", price: 600, effect: ItemEffect.POKE_BALL, param: 150, pocket: ItemPocket.BALL, description: "A good BALL with a higher catch rate than a POKé BALL." },
    [Item.POKE_BALL]: { name: "POKé BALL", price: 200, effect: ItemEffect.POKE_BALL, param: 100, pocket: ItemPocket.BALL, description: "A tool for catching wild POKéMON." },
    [Item.TOWN_MAP]: { name: "TOWN MAP", price: 0, effect: ItemEffect.TOWN_MAP, param: 0, pocket: ItemPocket.KEY_ITEM, description: "A map of the JOHTO region." },
    [Item.BICYCLE]: { name: "BICYCLE", price: 0, effect: ItemEffect.BICYCLE, param: 0, pocket: ItemPocket.KEY_ITEM, description: "A collapsible bike for fast movement." },
    [Item.MOON_STONE]: { name: "MOON STONE", price: 0, effect: ItemEffect.EVO_STONE, param: 0, pocket: ItemPocket.ITEM, description: "Evolves certain POKéMON." },
    [Item.ANTIDOTE]: { name: "ANTIDOTE", price: 100, effect: ItemEffect.STATUS_HEAL, param: 0, pocket: ItemPocket.ITEM, description: "Heals a poisoned POKéMON." },
    [Item.BURN_HEAL]: { name: "BURN HEAL", price: 250, effect: ItemEffect.STATUS_HEAL, param: 0, pocket: ItemPocket.ITEM, description: "Heals a POKéMON of a burn." },
    [Item.ICE_HEAL]: { name: "ICE HEAL", price: 250, effect: ItemEffect.STATUS_HEAL, param: 0, pocket: ItemPocket.ITEM, description: "Defrosts a frozen POKéMON." },
    [Item.AWAKENING]: { name: "AWAKENING", price: 250, effect: ItemEffect.STATUS_HEAL, param: 0, pocket: ItemPocket.ITEM, description: "Awakens a sleeping POKéMON." },
    [Item.PARLYZ_HEAL]: { name: "PARLYZ HEAL", price: 200, effect: ItemEffect.STATUS_HEAL, param: 0, pocket: ItemPocket.ITEM, description: "Heals a paralyzed POKéMON." },
    [Item.FULL_RESTORE]: { name: "FULL RESTORE", price: 3000, effect: ItemEffect.FULL_RESTORE, param: 0, pocket: ItemPocket.ITEM, description: "Fully restores HP and status." },
    [Item.MAX_POTION]: { name: "MAX POTION", price: 2500, effect: ItemEffect.RESTORE_HP, param: 255, pocket: ItemPocket.ITEM, description: "Fully restores HP." },
    [Item.HYPER_POTION]: { name: "HYPER POTION", price: 1200, effect: ItemEffect.RESTORE_HP, param: 200, pocket: ItemPocket.ITEM, description: "Restores POKéMON HP by 200." },
    [Item.SUPER_POTION]: { name: "SUPER POTION", price: 700, effect: ItemEffect.RESTORE_HP, param: 50, pocket: ItemPocket.ITEM, description: "Restores POKéMON HP by 50." },
    [Item.POTION]: { name: "POTION", price: 300, effect: ItemEffect.RESTORE_HP, param: 20, pocket: ItemPocket.ITEM, description: "Restores POKéMON HP by 20." },
    [Item.ESCAPE_ROPE]: { name: "ESCAPE ROPE", price: 550, effect: ItemEffect.ESCAPE_ROPE, param: 0, pocket: ItemPocket.ITEM, description: "Use to escape from a cave or dungeon." },
    [Item.REPEL]: { name: "REPEL", price: 350, effect: ItemEffect.REPEL, param: 100, pocket: ItemPocket.ITEM, description: "Repels wild POKéMON for 100 steps." },
    [Item.MAX_ELIXER]: { name: "MAX ELIXER", price: 0, effect: ItemEffect.RESTORE_PP, param: 99, pocket: ItemPocket.ITEM, description: "Fully restores PP of one POKéMON." },
    [Item.FIRE_STONE]: { name: "FIRE STONE", price: 0, effect: ItemEffect.EVO_STONE, param: 0, pocket: ItemPocket.ITEM, description: "Evolves certain POKéMON." },
    [Item.THUNDER_STONE]: { name: "THUNDERSTONE", asm_name: "THUNDERSTONE", price: 0, effect: ItemEffect.EVO_STONE, param: 0, pocket: ItemPocket.ITEM, description: "Evolves certain POKéMON." },
    [Item.WATER_STONE]: { name: "WATER STONE", price: 0, effect: ItemEffect.EVO_STONE, param: 0, pocket: ItemPocket.ITEM, description: "Evolves certain POKéMON." },
    [Item.HP_UP]: { name: "HP UP", price: 9800, effect: ItemEffect.VITAMIN, param: 0, pocket: ItemPocket.ITEM, description: "Raises the HP of one POKéMON." },
    [Item.PROTEIN]: { name: "PROTEIN", price: 9800, effect: ItemEffect.VITAMIN, param: 0, pocket: ItemPocket.ITEM, description: "Raises ATTACK of one POKéMON." },
    [Item.IRON]: { name: "IRON", price: 9800, effect: ItemEffect.VITAMIN, param: 0, pocket: ItemPocket.ITEM, description: "Raises DEFENSE of one POKéMON." },
    [Item.CARBOS]: { name: "CARBOS", price: 9800, effect: ItemEffect.VITAMIN, param: 0, pocket: ItemPocket.ITEM, description: "Raises SPEED of one POKéMON." },
    [Item.CALCIUM]: { name: "CALCIUM", price: 9800, effect: ItemEffect.VITAMIN, param: 0, pocket: ItemPocket.ITEM, description: "Raises SPECIAL of one POKéMON." },
    [Item.RARE_CANDY]: { name: "RARE CANDY", price: 4800, effect: ItemEffect.RARE_CANDY, param: 0, pocket: ItemPocket.ITEM, description: "Raises the level of a POKéMON by one." },
    [Item.X_ACCURACY]: { name: "X ACCURACY", price: 950, effect: ItemEffect.X_ACCURACY, param: 0, pocket: ItemPocket.ITEM, description: "Raises ACCURACY during one battle." },
    [Item.LEAF_STONE]: { name: "LEAF STONE", price: 0, effect: ItemEffect.EVO_STONE, param: 0, pocket: ItemPocket.ITEM, description: "Evolves certain POKéMON." },
    [Item.METAL_POWDER]: { name: "METAL POWDER", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that raises DITTO's DEFENSE." },
    [Item.NUGGET]: { name: "NUGGET", price: 5000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A solid gold nugget. Sell high." },
    [Item.POKE_DOLL]: { name: "POKé DOLL", price: 1000, effect: ItemEffect.POKE_DOLL, param: 0, pocket: ItemPocket.ITEM, description: "Use to escape from a wild POKéMON." },
    [Item.FULL_HEAL]: { name: "FULL HEAL", price: 600, effect: ItemEffect.STATUS_HEAL, param: 0, pocket: ItemPocket.ITEM, description: "Heals all status problems." },
    [Item.REVIVE]: { name: "REVIVE", price: 1500, effect: ItemEffect.REVIVE, param: 0, pocket: ItemPocket.ITEM, description: "Revives a fainted POKéMON with half HP." },
    [Item.MAX_REVIVE]: { name: "MAX REVIVE", price: 0, effect: ItemEffect.REVIVE, param: 0, pocket: ItemPocket.ITEM, description: "Fully revives a fainted POKéMON." },
    [Item.GUARD_SPEC]: { name: "GUARD SPEC.", price: 700, effect: ItemEffect.GUARD_SPEC, param: 0, pocket: ItemPocket.ITEM, description: "Prevents stats from being lowered for five turns." },
    [Item.SUPER_REPEL]: { name: "SUPER REPEL", price: 500, effect: ItemEffect.SUPER_REPEL, param: 200, pocket: ItemPocket.ITEM, description: "Repels wild POKéMON for 200 steps." },
    [Item.MAX_REPEL]: { name: "MAX REPEL", price: 700, effect: ItemEffect.MAX_REPEL, param: 250, pocket: ItemPocket.ITEM, description: "Repels wild POKéMON for 250 steps." },
    [Item.DIRE_HIT]: { name: "DIRE HIT", price: 650, effect: ItemEffect.DIRE_HIT, param: 0, pocket: ItemPocket.ITEM, description: "Raises critical hit ratio during one battle." },
    [Item.FRESH_WATER]: { name: "FRESH WATER", price: 200, effect: ItemEffect.RESTORE_HP, param: 50, pocket: ItemPocket.ITEM, description: "Restores POKéMON HP by 50." },
    [Item.SODA_POP]: { name: "SODA POP", price: 300, effect: ItemEffect.RESTORE_HP, param: 60, pocket: ItemPocket.ITEM, description: "Restores POKéMON HP by 60." },
    [Item.LEMONADE]: { name: "LEMONADE", price: 350, effect: ItemEffect.RESTORE_HP, param: 80, pocket: ItemPocket.ITEM, description: "Restores POKéMON HP by 80." },
    [Item.X_ATTACK]: { name: "X ATTACK", price: 500, effect: ItemEffect.X_ITEM, param: 0, pocket: ItemPocket.ITEM, description: "Raises ATTACK during one battle." },
    [Item.X_DEFEND]: { name: "X DEFEND", price: 550, effect: ItemEffect.X_ITEM, param: 0, pocket: ItemPocket.ITEM, description: "Raises DEFENSE during one battle." },
    [Item.X_SPEED]: { name: "X SPEED", price: 350, effect: ItemEffect.X_ITEM, param: 0, pocket: ItemPocket.ITEM, description: "Raises SPEED during one battle." },
    [Item.X_SPECIAL]: { name: "X SPECIAL", price: 350, effect: ItemEffect.X_ITEM, param: 0, pocket: ItemPocket.ITEM, description: "Raises SPCL. ATK during one battle." },
    [Item.COIN_CASE]: { name: "COIN CASE", price: 0, effect: ItemEffect.COIN_CASE, param: 0, pocket: ItemPocket.KEY_ITEM, description: "Holds up to 9,999 coins." },
    [Item.ITEMFINDER]: { name: "ITEMFINDER", price: 0, effect: ItemEffect.ITEMFINDER, param: 0, pocket: ItemPocket.KEY_ITEM, description: "Checks for hidden items in the area." },
    [Item.POKE_FLUTE]: { name: "POKé FLUTE", price: 0, effect: ItemEffect.POKE_FLUTE, param: 0, pocket: ItemPocket.ITEM, description: "A flute that awakens POKéMON." },
    [Item.SILVER_LEAF]: { name: "SILVER LEAF", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A strange silver-colored leaf." },
    [Item.EXP_SHARE]: { name: "EXP. SHARE", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that shares EXP. points." },
    [Item.OLD_ROD]: { name: "OLD ROD", price: 0, effect: ItemEffect.OLD_ROD, param: 0, pocket: ItemPocket.KEY_ITEM, description: "A shabby fishing rod. Use by water." },
    [Item.GOOD_ROD]: { name: "GOOD ROD", price: 0, effect: ItemEffect.GOOD_ROD, param: 0, pocket: ItemPocket.KEY_ITEM, description: "A good fishing rod. Use by water." },
    [Item.SILVER_WING]: { name: "SILVER WING", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A strange silver-colored feather." },
    [Item.SUPER_ROD]: { name: "SUPER ROD", price: 0, effect: ItemEffect.SUPER_ROD, param: 0, pocket: ItemPocket.KEY_ITEM, description: "An awesome fishing rod. Use by water." },
    [Item.RED_SCALE]: { name: "RED SCALE", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A scale from the red GYARADOS." },
    [Item.SECRET_POTION]: { name: "SECRETPOTION", asm_name: "SECRETPOTION", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.KEY_ITEM, description: "A secret medicine for sick POKéMON." },
    [Item.S_S_TICKET]: { name: "S.S. TICKET", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.KEY_ITEM, description: "A ticket for the S.S. AQUA." },
    [Item.MYSTERY_EGG]: { name: "MYSTERY EGG", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.KEY_ITEM, description: "An EGG obtained from Mr. POKéMON." },
    [Item.CLEAR_BELL]: { name: "CLEAR BELL", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.KEY_ITEM, description: "A clear bell." },
    [Item.SILVER_WING_2]: { name: "SILVER WING", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A strange silver-colored feather." },
    [Item.GOLD_LEAF]: { name: "GOLD LEAF", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A strange gold-colored leaf." },
    [Item.SLOWPOKE_TAIL]: { name: "SLOWPOKETAIL", asm_name: "SLOWPOKETAIL", price: 9800, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A very tasty tail. Sell high." },
    [Item.BRIGHT_POWDER]: { name: "BRIGHTPOWDER", asm_name: "BRIGHTPOWDER", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that lowers the foe's accuracy." },
    [Item.QUICK_CLAW]: { name: "QUICK CLAW", price: 0, effect: ItemEffect.NONE, param: 60, pocket: ItemPocket.ITEM, description: "A hold item that occasionally allows the first strike.", held_effect: "HELD_QUICK_CLAW" },
    [Item.AMULET_COIN]: { name: "AMULET COIN", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that doubles battle money." },
    [Item.EVERSTONE]: { name: "EVERSTONE", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that prevents evolution." },
    [Item.FOCUS_BAND]: { name: "FOCUS BAND", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that may prevent fainting." },
    [Item.EGG_TICKET]: { name: "EGG TICKET", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.KEY_ITEM, description: "A ticket for an EGG." },
    [Item.CARD_KEY]: { name: "CARD KEY", price: 0, effect: ItemEffect.CARD_KEY, param: 0, pocket: ItemPocket.KEY_ITEM, description: "A keycard that opens doors in the RADIO TOWER." },
    [Item.BASEMENT_KEY]: { name: "BASEMENT KEY", price: 0, effect: ItemEffect.BASEMENT_KEY, param: 0, pocket: ItemPocket.KEY_ITEM, description: "A key that opens doors in the GOLDENROD TUNNEL." },
    [Item.SQUIRT_BOTTLE]: { name: "SQUIRTBOTTLE", asm_name: "SQUIRTBOTTLE", price: 0, effect: ItemEffect.SQUIRTBOTTLE, param: 0, pocket: ItemPocket.KEY_ITEM, description: "A bottle for watering plants." },
    [Item.BLUE_CARD]: { name: "BLUE CARD", price: 0, effect: ItemEffect.BLUE_CARD, param: 0, pocket: ItemPocket.KEY_ITEM, description: "Card to save points.", held_effect: "HELD_NONE" },
    [Item.KINGS_ROCK]: { name: "KING'S ROCK", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that may cause flinching." },
    [Item.BERRY]: { name: "BERRY", price: 0, effect: ItemEffect.RESTORE_HP, param: 10, pocket: ItemPocket.ITEM, description: "A hold item that restores HP by 10." },
    [Item.GOLD_BERRY]: { name: "GOLD BERRY", price: 0, effect: ItemEffect.RESTORE_HP, param: 30, pocket: ItemPocket.ITEM, description: "A hold item that restores HP by 30." },
    [Item.MIRACLE_SEED]: { name: "MIRACLE SEED", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that boosts GRASS-type moves." },
    [Item.THICK_CLUB]: { name: "THICK CLUB", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that raises CUBONE's ATTACK." },
    [Item.BLACK_BELT]: { name: "BLACKBELT", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that boosts FIGHTING-type moves." },
    [Item.BLACK_GLASSES]: { name: "BLACKGLASSES", asm_name: "BLACKGLASSES", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that boosts DARK-type moves." },
    [Item.NEVER_MELT_ICE]: { name: "NEVERMELTICE", asm_name: "NEVERMELTICE", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that boosts ICE-type moves." },
    [Item.PINK_BOW]: { name: "PINK BOW", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that boosts NORMAL-type moves." },
    [Item.POISON_BARB]: { name: "POISON BARB", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that boosts POISON-type moves." },
    [Item.SOFT_SAND]: { name: "SOFT SAND", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that boosts GROUND-type moves." },
    [Item.SPELL_TAG]: { name: "SPELL TAG", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that boosts GHOST-type moves." },
    [Item.TWISTED_SPOON]: { name: "TWISTEDSPOON", asm_name: "TWISTEDSPOON", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that boosts PSYCHIC-type moves." },
    [Item.METAL_COAT]: { name: "METAL COAT", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that boosts STEEL-type moves." },
    [Item.DRAGON_FANG]: { name: "DRAGON FANG", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that boosts DRAGON-type moves.", held_effect: "HELD_DRAGON_BOOST" },
    [Item.LEFTOVERS]: { name: "LEFTOVERS", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that gradually restores HP." },
    [Item.MYSTERY_BERRY]: { name: "MYSTERYBERRY", asm_name: "MYSTERYBERRY", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that restores PP." },
    [Item.DRAGON_SCALE]: { name: "DRAGON SCALE", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item for SEADRA." },
    [Item.BERSERK_GENE]: { name: "BERSERK GENE", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that sharply boosts ATTACK but causes confusion.", held_effect: "HELD_ATTACK_UP" },
    [Item.SACRED_ASH]: { name: "SACRED ASH", price: 0, effect: ItemEffect.SACRED_ASH, param: 0, pocket: ItemPocket.ITEM, description: "Fully revives all fainted POKéMON." },
    [Item.HEAVY_BALL]: { name: "HEAVY BALL", price: 0, effect: ItemEffect.POKE_BALL, param: 0, pocket: ItemPocket.BALL, description: "A BALL for catching heavy POKéMON." },
    [Item.FLOWER_MAIL]: { name: "FLOWER MAIL", price: 50, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "POKéMON-held mail." },
    [Item.LEVEL_BALL]: { name: "LEVEL BALL", price: 0, effect: ItemEffect.POKE_BALL, param: 0, pocket: ItemPocket.BALL, description: "A BALL for catching lower-level POKéMON." },
    [Item.LURE_BALL]: { name: "LURE BALL", price: 0, effect: ItemEffect.POKE_BALL, param: 0, pocket: ItemPocket.BALL, description: "A BALL for catching hooked POKéMON." },
    [Item.FAST_BALL]: { name: "FAST BALL", price: 0, effect: ItemEffect.POKE_BALL, param: 0, pocket: ItemPocket.BALL, description: "A BALL for catching fast POKéMON." },
    [Item.FRIEND_BALL]: { name: "FRIEND BALL", price: 0, effect: ItemEffect.POKE_BALL, param: 0, pocket: ItemPocket.BALL, description: "A BALL that makes POKéMON friendly." },
    [Item.MOON_BALL]: { name: "MOON BALL", price: 0, effect: ItemEffect.POKE_BALL, param: 0, pocket: ItemPocket.BALL, description: "A BALL for MOON STONE evolvers." },
    [Item.LOVE_BALL]: { name: "LOVE BALL", price: 0, effect: ItemEffect.POKE_BALL, param: 0, pocket: ItemPocket.BALL, description: "For POKéMON of the opposite gender." },
    [Item.NORMAL_BOX]: { name: "NORMAL BOX", price: 0, effect: ItemEffect.NORMAL_BOX, param: 0, pocket: ItemPocket.ITEM, description: "A box for storing items." },
    [Item.GORGEOUS_BOX]: { name: "GORGEOUS BOX", price: 0, effect: ItemEffect.GORGEOUS_BOX, param: 0, pocket: ItemPocket.ITEM, description: "A gorgeous box for storing items." },
    [Item.SUN_STONE]: { name: "SUN STONE", price: 0, effect: ItemEffect.EVO_STONE, param: 0, pocket: ItemPocket.ITEM, description: "Evolves certain POKéMON." },
    [Item.POLKADOT_BOW]: { name: "POLKADOT BOW", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that boosts NORMAL-type moves." },
    [Item.UP_GRADE]: { name: "UP-GRADE", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item for PORYGON." },
    [Item.BERRY_JUICE]: { name: "BERRY JUICE", price: 100, effect: ItemEffect.RESTORE_HP, param: 20, pocket: ItemPocket.ITEM, description: "A hold item that restores HP by 20." },
    [Item.PRZCURE_BERRY]: { name: "PRZCUREBERRY", asm_name: "PRZCUREBERRY", price: 0, effect: ItemEffect.STATUS_HEAL, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that heals paralysis.", held_effect: "HELD_HEAL_PARALYZE" },
    [Item.PSNCURE_BERRY]: { name: "PSNCUREBERRY", asm_name: "PSNCUREBERRY", price: 0, effect: ItemEffect.STATUS_HEAL, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that heals poison.", held_effect: "HELD_HEAL_POISON" },
    [Item.ICE_BERRY]: { name: "ICE BERRY", price: 0, effect: ItemEffect.STATUS_HEAL, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that defrosts.", held_effect: "HELD_HEAL_FREEZE" },
    [Item.MINT_BERRY]: { name: "MINT BERRY", price: 0, effect: ItemEffect.STATUS_HEAL, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that awakens.", held_effect: "HELD_HEAL_SLEEP" },
    [Item.BURNT_BERRY]: { name: "BURNT BERRY", price: 0, effect: ItemEffect.STATUS_HEAL, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that heals a burn.", held_effect: "HELD_HEAL_BURN" },
    [Item.BITTER_BERRY]: { name: "BITTER BERRY", price: 0, effect: ItemEffect.BITTER_BERRY, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that heals confusion.", held_effect: "HELD_HEAL_CONFUSION" },
    [Item.CHARCOAL]: { name: "CHARCOAL", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that boosts FIRE-type moves." },
    [Item.HARD_STONE]: { name: "HARD STONE", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that boosts ROCK-type moves." },
    [Item.MAGNET]: { name: "MAGNET", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that boosts ELECTRIC-type moves." },
    [Item.MIRACLE_BERRY]: { name: "MIRACLEBERRY", asm_name: "MIRACLEBERRY", price: 0, effect: ItemEffect.STATUS_HEAL, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that heals all status problems.", held_effect: "HELD_HEAL_STATUS" },
    [Item.LUCKY_PUNCH]: { name: "LUCKY PUNCH", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that raises CHANSEY's critical hit ratio." },
    [Item.METAL_POWDER_2]: { name: "METAL POWDER", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that raises DITTO's DEFENSE." },
    [Item.STICK]: { name: "STICK", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that raises FARFETCH'D's critical hit ratio." },
    [Item.SCOPE_LENS]: { name: "SCOPE LENS", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that raises the critical hit ratio." },
    [Item.CLEANSE_TAG]: { name: "CLEANSE TAG", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that helps repel wild POKéMON." },
    [Item.SMOKE_BALL]: { name: "SMOKE BALL", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that assures escape from wild POKéMON.", held_effect: "HELD_ESCAPE" },
    [Item.LIGHT_BALL]: { name: "LIGHT BALL", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that raises PIKACHU's SPECIAL." },
    [Item.LUCKY_EGG]: { name: "LUCKY EGG", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hold item that boosts EXP. points." },
    [Item.PARK_BALL]: { name: "PARK BALL", price: 0, effect: ItemEffect.POKE_BALL, param: 255, pocket: ItemPocket.BALL, description: "A special BALL for the BUG-CATCHING CONTEST." },
    [Item.RAINBOW_WING]: { name: "RAINBOW WING", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A strange rainbow-colored feather." },
    [Item.BRICK_PIECE]: { name: "BRICK PIECE", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A small piece of brick." },
    [Item.SURF_MAIL]: { name: "SURF MAIL", price: 50, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "POKéMON-held mail." },
    [Item.LITEBLUEMAIL]: { name: "LITEBLUEMAIL", price: 50, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "POKéMON-held mail." },
    [Item.PORTRAITMAIL]: { name: "PORTRAITMAIL", price: 50, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "POKéMON-held mail." },
    [Item.LOVELY_MAIL]: { name: "LOVELY MAIL", price: 50, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "POKéMON-held mail." },
    [Item.EON_MAIL]: { name: "EON MAIL", price: 50, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "POKéMON-held mail." },
    [Item.MORPH_MAIL]: { name: "MORPH MAIL", price: 50, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "POKéMON-held mail." },
    [Item.BLUESKY_MAIL]: { name: "BLUESKY MAIL", price: 50, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "POKéMON-held mail." },
    [Item.MUSIC_MAIL]: { name: "MUSIC MAIL", price: 50, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "POKéMON-held mail." },
    [Item.MIRAGE_MAIL]: { name: "MIRAGE MAIL", price: 50, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "POKéMON-held mail." },
    [Item.BIG_MUSHROOM]: { name: "BIG MUSHROOM", price: 5000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A rare mushroom. Sell high.", held_effect: "HELD_NONE" },
    [Item.BIG_PEARL]: { name: "BIG PEARL", price: 7500, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A big, beautiful pearl. Sell high.", held_effect: "HELD_NONE" },
    [Item.BLACKBELT_I]: { name: "BLACKBELT I", price: 100, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "Boosts fighting-type moves. (HOLD)", held_effect: "HELD_FIGHTING_BOOST" },
    [Item.BLK_APRICORN]: { name: "BLK APRICORN", price: 200, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A black APRICORN.", held_effect: "HELD_NONE" },
    [Item.BLU_APRICORN]: { name: "BLU APRICORN", price: 200, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A blue APRICORN.", held_effect: "HELD_NONE" },
    [Item.ELIXER]: { name: "ELIXER", price: 3000, effect: ItemEffect.RESTORE_PP, param: 10, pocket: ItemPocket.ITEM, description: "Restores PP of all moves by 10.", held_effect: "HELD_NONE" },
    [Item.ENERGYPOWDER]: { name: "ENERGYPOWDER", price: 500, effect: ItemEffect.RESTORE_HP, param: 50, pocket: ItemPocket.ITEM, description: "Restores #MON HP by 50. Bitter.", held_effect: "HELD_NONE" },
    [Item.GS_BALL]: { name: "GS BALL", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.KEY_ITEM, description: "The mysterious BALL.", held_effect: "HELD_NONE" },
    [Item.GRN_APRICORN]: { name: "GRN APRICORN", price: 200, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A green APRICORN.", held_effect: "HELD_NONE" },
    [Item.LOST_ITEM]: { name: "LOST ITEM", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.KEY_ITEM, description: "The # DOLL lost by the COPYCAT.", held_effect: "HELD_NONE" },
    [Item.MACHINE_PART]: { name: "MACHINE PART", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.KEY_ITEM, description: "A machine part for the POWER PLANT.", held_effect: "HELD_NONE" },
    [Item.MAX_ETHER]: { name: "MAX ETHER", price: 2000, effect: ItemEffect.RESTORE_PP, param: -1, pocket: ItemPocket.ITEM, description: "Fully restores PP of one move.", held_effect: "HELD_NONE" },
    [Item.MOOMOO_MILK]: { name: "MOOMOO MILK", price: 500, effect: ItemEffect.RESTORE_HP, param: 100, pocket: ItemPocket.ITEM, description: "Restores #MON HP by 100.", held_effect: "HELD_NONE" },
    [Item.MYSTIC_WATER]: { name: "MYSTIC WATER", price: 100, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "Powers up water- type moves. (HOLD)", held_effect: "HELD_WATER_BOOST" },
    [Item.PASS]: { name: "PASS", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.KEY_ITEM, description: "A ticket for the MAGNET TRAIN.", held_effect: "HELD_NONE" },
    [Item.PEARL]: { name: "PEARL", price: 1400, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A beautiful pearl. Sell low.", held_effect: "HELD_NONE" },
    [Item.PNK_APRICORN]: { name: "PNK APRICORN", price: 200, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A pink APRICORN.", held_effect: "HELD_NONE" },
    [Item.PP_UP]: { name: "PP UP", price: 9800, effect: ItemEffect.PP_UP, param: 0, pocket: ItemPocket.ITEM, description: "Raises max PP of a selected move.", held_effect: "HELD_NONE" },
    [Item.ETHER]: { name: "ETHER", price: 1200, effect: ItemEffect.RESTORE_PP, param: 10, pocket: ItemPocket.ITEM, description: "Restores PP of one move by 10.", held_effect: "HELD_NONE" },
    [Item.ENERGY_ROOT]: { name: "ENERGY ROOT", price: 800, effect: ItemEffect.RESTORE_HP, param: 200, pocket: ItemPocket.ITEM, description: "Restores #MON HP by 200. Bitter.", held_effect: "HELD_NONE" },
    [Item.HEAL_POWDER]: { name: "HEAL POWDER", price: 450, effect: ItemEffect.STATUS_HEAL, param: 0, pocket: ItemPocket.ITEM, description: "Cures all status problems. Bitter.", held_effect: "HELD_NONE" },
    [Item.REVIVAL_HERB]: { name: "REVIVAL HERB", price: 2800, effect: ItemEffect.REVIVE, param: 0, pocket: ItemPocket.ITEM, description: "Revives a fainted #MON. Bitter.", held_effect: "HELD_NONE" },
    [Item.RAGECANDYBAR]: { name: "RAGECANDYBAR", price: 300, effect: ItemEffect.RESTORE_HP, param: 20, pocket: ItemPocket.ITEM, description: "Restores #MON HP by 20.", held_effect: "HELD_NONE" },
    [Item.RED_APRICORN]: { name: "RED APRICORN", price: 200, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A red APRICORN.", held_effect: "HELD_NONE" },
    [Item.SILVERPOWDER]: { name: "SILVERPOWDER", price: 100, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "Powers up bug-type moves. (HOLD)", held_effect: "HELD_BUG_BOOST" },
    [Item.SHARP_BEAK]: { name: "SHARP BEAK", price: 100, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "Powers up flying- type moves. (HOLD)", held_effect: "HELD_FLYING_BOOST" },
    [Item.STARDUST]: { name: "STARDUST", price: 2000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "Pretty, red sand. Sell high.", held_effect: "HELD_NONE" },
    [Item.STAR_PIECE]: { name: "STAR PIECE", price: 9800, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A hunk of red gem. Sell very high.", held_effect: "HELD_NONE" },
    [Item.TINYMUSHROOM]: { name: "TINYMUSHROOM", price: 500, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "An ordinary mush- room. Sell low.", held_effect: "HELD_NONE" },
    [Item.WHT_APRICORN]: { name: "WHT APRICORN", price: 200, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A white APRICORN.", held_effect: "HELD_NONE" },
    [Item.YLW_APRICORN]: { name: "YLW APRICORN", price: 200, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.ITEM, description: "A yellow APRICORN.", held_effect: "HELD_NONE" },
    [Item.TM_HM_01]: { name: "TM01", price: 3000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches DYNAMICPUNCH." },
    [Item.TM_HM_02]: { name: "TM02", price: 2000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches HEADBUTT." },
    [Item.TM_HM_03]: { name: "TM03", price: 2000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches CURSE." },
    [Item.TM_HM_04]: { name: "TM04", price: 2000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches ROLLOUT." },
    [Item.TM_HM_05]: { name: "TM05", price: 1000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches ROAR." },
    [Item.TM_HM_06]: { name: "TM06", price: 3000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches TOXIC." },
    [Item.TM_HM_07]: { name: "TM07", price: 3000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches ZAP CANNON." },
    [Item.TM_HM_08]: { name: "TM08", price: 1000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches ROCK SMASH." },
    [Item.TM_HM_09]: { name: "TM09", price: 2000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches PSYCH UP." },
    [Item.TM_HM_10]: { name: "TM10", price: 3000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches HIDDEN POWER." },
    [Item.TM_HM_11]: { name: "TM11", price: 2000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches SUNNY DAY." },
    [Item.TM_HM_12]: { name: "TM12", price: 2000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches SWEET SCENT." },
    [Item.TM_HM_13]: { name: "TM13", price: 1000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches SNORE." },
    [Item.TM_HM_14]: { name: "TM14", price: 5500, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches BLIZZARD." },
    [Item.TM_HM_15]: { name: "TM15", price: 7500, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches HYPER BEAM." },
    [Item.TM_HM_16]: { name: "TM16", price: 5500, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches ICY WIND." },
    [Item.TM_HM_17]: { name: "TM17", price: 3000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches PROTECT." },
    [Item.TM_HM_18]: { name: "TM18", price: 2000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches RAIN DANCE." },
    [Item.TM_HM_19]: { name: "TM19", price: 3000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches GIGA DRAIN." },
    [Item.TM_HM_20]: { name: "TM20", price: 3000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches ENDURE." },
    [Item.TM_HM_21]: { name: "TM21", price: 1000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches FRUSTRATION." },
    [Item.TM_HM_22]: { name: "TM22", price: 3000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches SOLARBEAM." },
    [Item.TM_HM_23]: { name: "TM23", price: 3000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches IRON TAIL." },
    [Item.TM_HM_24]: { name: "TM24", price: 3000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches DRAGONBREATH." },
    [Item.TM_HM_25]: { name: "TM25", price: 5500, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches THUNDER." },
    [Item.TM_HM_26]: { name: "TM26", price: 3000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches EARTHQUAKE." },
    [Item.TM_HM_27]: { name: "TM27", price: 1000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches RETURN." },
    [Item.TM_HM_28]: { name: "TM28", price: 2000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches DIG." },
    [Item.TM_HM_29]: { name: "TM29", price: 3000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches PSYCHIC." },
    [Item.TM_HM_30]: { name: "TM30", price: 3000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches SHADOW BALL." },
    [Item.TM_HM_31]: { name: "TM31", price: 3000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches MUD-SLAP." },
    [Item.TM_HM_32]: { name: "TM32", price: 1000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches DOUBLE TEAM." },
    [Item.TM_HM_33]: { name: "TM33", price: 2000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches ICE PUNCH." },
    [Item.TM_HM_34]: { name: "TM34", price: 1000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches SWAGGER." },
    [Item.TM_HM_35]: { name: "TM35", price: 1000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches SLEEP TALK." },
    [Item.TM_HM_36]: { name: "TM36", price: 3000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches SLUDGE BOMB." },
    [Item.TM_HM_37]: { name: "TM37", price: 2000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches SANDSTORM." },
    [Item.TM_HM_38]: { name: "TM38", price: 5500, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches FIRE BLAST." },
    [Item.TM_HM_39]: { name: "TM39", price: 1000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches SWIFT." },
    [Item.TM_HM_40]: { name: "TM40", price: 1000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches DEFENSE CURL." },
    [Item.TM_HM_41]: { name: "TM41", price: 2000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches THUNDERPUNCH." },
    [Item.TM_HM_42]: { name: "TM42", price: 3000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches DREAM EATER." },
    [Item.TM_HM_43]: { name: "TM43", price: 3000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches DETECT." },
    [Item.TM_HM_44]: { name: "TM44", price: 3000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches REST." },
    [Item.TM_HM_45]: { name: "TM45", price: 3000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches ATTRACT." },
    [Item.TM_HM_46]: { name: "TM46", price: 3000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches THIEF." },
    [Item.TM_HM_47]: { name: "TM47", price: 3000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches STEEL WING." },
    [Item.TM_HM_48]: { name: "TM48", price: 2000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches FIRE PUNCH." },
    [Item.TM_HM_49]: { name: "TM49", price: 3000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches FURY CUTTER." },
    [Item.TM_HM_50]: { name: "TM50", price: 1000, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches NIGHTMARE." },
    [Item.TM_HM_51]: { name: "HM01", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches CUT." },
    [Item.TM_HM_52]: { name: "HM02", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches FLY." },
    [Item.TM_HM_53]: { name: "HM03", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches SURF." },
    [Item.TM_HM_54]: { name: "HM04", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches STRENGTH." },
    [Item.TM_HM_55]: { name: "HM05", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches FLASH." },
    [Item.TM_HM_56]: { name: "HM06", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches WHIRLPOOL." },
    [Item.TM_HM_57]: { name: "HM07", price: 0, effect: ItemEffect.NONE, param: 0, pocket: ItemPocket.TM_HM, description: "Teaches WATERFALL." },
};

const toGeneratedItemRecord = (script_name: string, data: ItemSeed): ItemType =>
    ItemSchema.parse({
        name: data.name,
        script_name,
        description: data.description,
        effect: data.effect,
        status_heals: [],
        revive_hp_percent: null,
        party_revive_hp_percent: null,
        pp_restore_scope: null,
        pp_restore_points: null,
        pp_up_stages: null,
        vitamin_stat: null,
        vitamin_stat_exp: null,
        vitamin_max_stat_exp: null,
        rare_candy_level_gain: null,
        battle_stat_boost_stat: null,
        battle_stat_boost_stages: null,
        battle_escape_mode: null,
        battle_focus_energy: null,
        battle_stat_drop_guard: null,
        confusion_heal: null,
        repel_steps: null,
        escape_rope_mode: null,
        price: data.price,
        held_effect: data.held_effect ?? "HELD_NONE",
        parameter: data.param,
        property: data.property ?? "",
        pocket: data.pocket,
        field_menu: data.field_menu ?? "",
        field_usable: (data.field_menu ?? "") !== "ITEMMENU_NOUSE" || data.effect === ItemEffect.TOWN_MAP,
        battle_menu: data.battle_menu ?? "",
        battle_usable: (data.battle_menu ?? "") !== "ITEMMENU_NOUSE",
        battle_capture_ball: data.effect === ItemEffect.POKE_BALL ? true : null,
        consumable: data.pocket === ItemPocket.BALL || data.field_menu !== "ITEMMENU_NOUSE" || data.battle_menu !== "ITEMMENU_NOUSE",
        tmhm_index: null,
        tmhm_move: null,
    });

export const items: ItemType[] = Object.entries(itemData).map(([script_name, data]) =>
    toGeneratedItemRecord(script_name as Item, data)
);

export const itemEffectsByAsmName = new Map(
    Object.entries(itemData).map(([script_name, data]) => [data.asm_name ?? script_name, String(data.effect)])
);

export function loadAllItems(): Record<string, ItemType> {
    const itemMap: Record<string, ItemType> = {};
    for (const item of items) {
        itemMap[item.name] = item;
    }
    return itemMap;
}
