
export const movementData: Record<string, string[]> = {
  NewBarkTown_TeacherRunsToYouMovement1: [
    "step LEFT",
    "step LEFT",
    "step LEFT",
    "step LEFT",
    "step_end",
  ],
  NewBarkTown_TeacherRunsToYouMovement2: [
    "step LEFT",
    "step LEFT",
    "step LEFT",
    "step LEFT",
    "step LEFT",
    "turn_head DOWN",
    "step_end",
  ],
  NewBarkTown_TeacherBringsYouBackMovement1: [
    "step RIGHT",
    "step RIGHT",
    "step RIGHT",
    "step RIGHT",
    "turn_head LEFT",
    "step_end",
  ],
  NewBarkTown_TeacherBringsYouBackMovement2: [
    "step RIGHT",
    "step RIGHT",
    "step RIGHT",
    "step RIGHT",
    "step RIGHT",
    "turn_head LEFT",
    "step_end",
  ],
  NewBarkTown_RivalPushesYouAwayMovement: [
    "turn_head UP",
    "step DOWN",
    "step_end",
  ],
  NewBarkTown_RivalShovesYouOutMovement: [
    "turn_head UP",
    "fix_facing",
    "jump_step DOWN",
    "remove_fixed_facing",
    "step_end",
  ],
  NewBarkTown_RivalReturnsToTheShadowsMovement: [
    "step RIGHT",
    "step_end",
  ],
  DudeMovementData1a: [
    "step UP",
    "step UP",
    "step UP",
    "step UP",
    "step RIGHT",
    "step RIGHT",
    "step_end",
  ],
  DudeMovementData2a: [
    "step UP",
    "step UP",
    "step UP",
    "step RIGHT",
    "step RIGHT",
    "step_end",
  ],
  DudeMovementData1b: [
    "step LEFT",
    "step LEFT",
    "step DOWN",
    "step DOWN",
    "step DOWN",
    "step DOWN",
    "step_end",
  ],
  DudeMovementData2b: [
    "step LEFT",
    "step LEFT",
    "step DOWN",
    "step DOWN",
    "step DOWN",
    "step_end",
  ],
  GuideGentMovement1: [
    "step LEFT",
    "step LEFT",
    "step UP",
    "step LEFT",
    "turn_head UP",
    "step_end",
  ],
  GuideGentMovement2: [
    "step LEFT",
    "step LEFT",
    "step LEFT",
    "step LEFT",
    "step LEFT",
    "step LEFT",
    "turn_head UP",
    "step_end",
  ],
  GuideGentMovement3: [
    "step LEFT",
    "step LEFT",
    "step LEFT",
    "step LEFT",
    "step LEFT",
    "step LEFT",
    "step LEFT",
    "turn_head UP",
    "step_end",
  ],
  GuideGentMovement4: [
    "step LEFT",
    "step LEFT",
    "step LEFT",
    "step DOWN",
    "step LEFT",
    "step LEFT",
    "step LEFT",
    "step DOWN",
    "turn_head LEFT",
    "step_end",
  ],
  GuideGentMovement5: [
    "step DOWN",
    "step DOWN",
    "step RIGHT",
    "step RIGHT",
    "step RIGHT",
    "step RIGHT",
    "step RIGHT",
    "step RIGHT",
    "step RIGHT",
    "step RIGHT",
    "step RIGHT",
    "step RIGHT",
    "step DOWN",
    "step DOWN",
    "step RIGHT",
    "step RIGHT",
    "step RIGHT",
    "step RIGHT",
    "step RIGHT",
    "turn_head UP",
    "step_end",
  ],
  GuideGentMovement6: [
    "step UP",
    "step UP",
    "step_end",
  ],
  CherrygroveCity_RivalWalksToYou: [
    "step LEFT",
    "step LEFT",
    "step LEFT",
    "step LEFT",
    "step LEFT",
    "step_end",
  ],
  CherrygroveCity_RivalPushesYouOutOfTheWay: [
    "big_step DOWN",
    "turn_head UP",
    "step_end",
  ],
  CherrygroveCity_RivalExitsStageLeft: [
    "big_step LEFT",
    "big_step LEFT",
    "big_step LEFT",
    "big_step LEFT",
    "big_step UP",
    "big_step UP",
    "big_step LEFT",
    "big_step LEFT",
    "step_end",
  ],
  Route30_JoeysRattataAttacksMovement: [
    "fix_facing",
    "big_step UP",
    "big_step DOWN",
    "step_end",
  ],
  Route30_MikeysRattataAttacksMovement: [
    "fix_facing",
    "big_step DOWN",
    "big_step UP",
    "step_end",
  ],
};
