import { MoveName } from "./enums/move";

// Data from Serebii for Pokemon Crystal
export const TMHM_MOVES = [
  MoveName.DYNAMICPUNCH, // TM01
  MoveName.HEADBUTT, // TM02
  MoveName.CURSE, // TM03
  MoveName.ROLLOUT, // TM04
  MoveName.ROAR, // TM05
  MoveName.TOXIC, // TM06
  MoveName.ZAP_CANNON, // TM07
  MoveName.ROCK_SMASH, // TM08
  MoveName.PSYCH_UP, // TM09
  MoveName.HIDDEN_POWER, // TM10
  MoveName.SUNNY_DAY, // TM11
  MoveName.SWEET_SCENT, // TM12
  MoveName.SNORE, // TM13
  MoveName.BLIZZARD, // TM14
  MoveName.HYPER_BEAM, // TM15
  MoveName.ICY_WIND, // TM16
  MoveName.PROTECT, // TM17
  MoveName.RAIN_DANCE, // TM18
  MoveName.GIGA_DRAIN, // TM19
  MoveName.ENDURE, // TM20
  MoveName.FRUSTRATION, // TM21
  MoveName.SOLARBEAM, // TM22
  MoveName.IRON_TAIL, // TM23
  MoveName.DRAGONBREATH, // TM24
  MoveName.THUNDER, // TM25
  MoveName.EARTHQUAKE, // TM26
  MoveName.RETURN, // TM27
  MoveName.DIG, // TM28
  MoveName.PSYCHIC_M, // TM29
  MoveName.SHADOW_BALL, // TM30
  MoveName.MUD_SLAP, // TM31
  MoveName.DOUBLE_TEAM, // TM32
  MoveName.ICE_PUNCH, // TM33
  MoveName.SWAGGER, // TM34
  MoveName.SLEEP_TALK, // TM35
  MoveName.SLUDGE_BOMB, // TM36
  MoveName.SANDSTORM, // TM37
  MoveName.FIRE_BLAST, // TM38
  MoveName.SWIFT, // TM39
  MoveName.DEFENSE_CURL, // TM40
  MoveName.THUNDERPUNCH, // TM41
  MoveName.DREAM_EATER, // TM42
  MoveName.DETECT, // TM43
  MoveName.REST, // TM44
  MoveName.ATTRACT, // TM45
  MoveName.THIEF, // TM46
  MoveName.STEEL_WING, // TM47
  MoveName.FIRE_PUNCH, // TM48
  MoveName.FURY_CUTTER, // TM49
  MoveName.NIGHTMARE, // TM50
  MoveName.CUT, // HM01
  MoveName.FLY, // HM02
  MoveName.SURF, // HM03
  MoveName.STRENGTH, // HM04
  MoveName.FLASH, // HM05
  MoveName.WHIRLPOOL, // HM06
  MoveName.WATERFALL, // HM07
];
