import { bank_of_mom } from './mom';
import { players_house_pc, pokemon_center_pc } from './pc';
import { play_cur_mon_cry, play_map_music, play_slow_cry, gameboy_check, fade_out_music, restart_map_music } from './audio';
import {
    battle_tower_action,
    battle_tower_battle,
    battle_tower_fade,
    battle_tower_mobile_error,
    battle_tower_room_menu,
    check_for_battle_tower_rules,
    menu_challenge_explanation_cancel,
} from './battle-tower';
import { ask_remember_password, buena_prize, buenas_password } from './buena';
import { gs_healings, ho_oh_chamber, heal_party, heal_machine_anim } from './misc';
import { select_apricorn_for_kurt } from './kurt';
import {
    ask_mobile_or_cable,
    cable_club_check_which_chris,
    check_both_selected_same_room,
    check_link_timeout_receptionist,
    close_link,
    set_bits_for_battle_request,
    set_bits_for_link_trade_request,
    set_bits_for_time_capsule_request,
    try_quick_save,
    wait_for_linked_friend,
    wait_for_other_player_to_exit,
} from './link';
import { check_magikarp_length, magikarp_house_sign } from './magikarp';
import { magnet_train } from './magnet-train';
import { check_mystery_gift, get_mystery_gift_item, unlock_mystery_gift } from './mystery-gift';
import { give_odd_egg } from './odd-egg';
import {
    bills_grandfather,
    celebi_shrine_event,
    colosseum,
    daisys_grooming,
    display_coin_case_balance,
    display_link_record,
    failed_link_to_past,
    load_opponent_trainer_and_pokemon_with_ot_sprite,
    move_deletion,
    older_haircut_brother,
    photo_studio,
    print_todays_lucky_number,
    prof_oaks_pc_boot,
    trade_center,
    younger_haircut_brother,
    name_rival,
    trainer_house,
    diploma,
    print_diploma,
    stubbed_trainer_rankings_healings,
} from './placeholders';
import {
    DayCareLady,
    DayCareMan,
    DayCareManOutside,
    DayCareMon1,
    DayCareMon2,
} from './day-care';
import {
    bug_contest_judging,
    bug_contest_set_caught_contest_mon,
    check_bug_contest_timer,
    check_party_full_after_contest,
    choose_wild_encounter_bug_contest,
    contest_drop_off_mons,
    contest_return_mons,
    give_park_balls,
    select_random_bug_contest_contestants,
    start_bug_contest_timer,
} from './bug-contest';
import { toggle_decorations_visibility, toggle_maptile_decorations } from './decorations';
import {
    card_flip_special,
    memory_game_special,
    slot_machine_ui_special,
    unown_puzzle_special,
} from './games';
import { give_dratini, give_shuckle, return_shuckie } from './gifts';
import {
    function1011f1,
    function101220,
    function101225,
    function101231,
    function103780,
    function1037c2,
    function1037eb,
    function10383c,
    function10387b,
    function1700ba,
    mobile_select_three_mons,
} from './placeholders-mobile';
import { set_player_palette } from './player';
import {
    activate_fishing_swarm,
    beasts_check,
    check_caught_celebi,
    check_first_mon_is_egg,
    get_first_pokemon_happiness,
    mon_check,
    find_party_mon_that_species,
    find_party_mon_that_species_your_trainer_id,
    game_corner_prize_mon_check_dex,
} from './pokemon';
import { init_roam_mons } from './roamers';
import { move_tutor, name_rater, poke_seer } from './services';
import { check_mobile_adapter_status_special, load_map_palettes, load_standing_sprites_gfx, load_used_sprites_gfx, load_walking_sprites_gfx, refresh_sprites, update_player_sprite, update_sprites } from './sprites';
import { reset_special } from './system';
import { initial_clear_dst_flag, initial_set_dst_flag, sample_kenji_break_countdown, set_day_of_week, update_time } from './time';
import { check_time_capsule_compatibility, enter_time_capsule, time_capsule } from './time-capsule';
import { aerodactyl_chamber, display_unown_words, kabuto_chamber, omanyte_chamber, unown_printer } from './unown';
import { fade_in_from_black, fade_in_from_white, fade_out_to_black, fade_out_to_white } from './graphics';
import { place_money_top_right, display_money_and_coin_balance } from './money';
import { check_for_lucky_number_winners, check_lucky_number_show_flag, reset_lucky_number_show_flag } from './lucky-number';
import { snorlax_awake } from './snorlax';
import type { SpecialFunction } from './special-types';

export const SPECIAL_FUNCTIONS = {
    "SetDayOfWeek": set_day_of_week,
    "InitialSetDSTFlag": initial_set_dst_flag,
    "InitialClearDSTFlag": initial_clear_dst_flag,
    "UpdateTime": update_time,
    "SampleKenjiBreakCountdown": sample_kenji_break_countdown,
    "BankOfMom": bank_of_mom,
    "PlayersHousePC": players_house_pc,
    "PokemonCenterPC": pokemon_center_pc,
    "PlayMapMusic": play_map_music,
    "RestartMapMusic": restart_map_music,
    "PlayCurMonCry": play_cur_mon_cry,
    "PlaySlowCry": play_slow_cry,
    "GameboyCheck": gameboy_check,
    "FadeOutMusic": fade_out_music,
    "GSHealings": gs_healings,
    "HoOhChamber": ho_oh_chamber,
    "HealParty": heal_party,
    "HealMachineAnim": heal_machine_anim,
    "SelectApricornForKurt": select_apricorn_for_kurt,
    "CheckMysteryGift": check_mystery_gift,
    "GetMysteryGiftItem": get_mystery_gift_item,
    "DayCareMan": DayCareMan,
    "DayCareLady": DayCareLady,
    "DayCareManOutside": DayCareManOutside,
    "DayCareMon1": DayCareMon1,
    "DayCareMon2": DayCareMon2,
    "UnlockMysteryGift": unlock_mystery_gift,
    "CheckMagikarpLength": check_magikarp_length,
    "MagikarpHouseSign": magikarp_house_sign,
    "GameCornerPrizeMonCheckDex": game_corner_prize_mon_check_dex,
    "DisplayUnownWords": display_unown_words,
    "OmanyteChamber": omanyte_chamber,
    "AerodactylChamber": aerodactyl_chamber,
    "KabutoChamber": kabuto_chamber,
    "UnownPrinter": unown_printer,
    "SlotMachine": slot_machine_ui_special,
    "CardFlip": card_flip_special,
    "MemoryGame": memory_game_special,
    "UnownPuzzle": unown_puzzle_special,
    "GetFirstPokemonHappiness": get_first_pokemon_happiness,
    "CheckFirstMonIsEgg": check_first_mon_is_egg,
    "FindPartyMonThatSpecies": find_party_mon_that_species,
    "FindPartyMonThatSpeciesYourTrainerID": find_party_mon_that_species_your_trainer_id,
    "ActivateFishingSwarm": activate_fishing_swarm,
    "CheckCaughtCelebi": check_caught_celebi,
    "BeastsCheck": beasts_check,
    "MonCheck": mon_check,
    "InitRoamMons": init_roam_mons,
    "SetPlayerPalette": set_player_palette,
    "LoadMapPalettes": load_map_palettes,
    "RefreshSprites": refresh_sprites,
    "UpdatePlayerSprite": update_player_sprite,
    "UpdateSprites": update_sprites,
    "ReloadSpritesNoPalettes": update_sprites,
    "CheckMobileAdapterStatusSpecial": check_mobile_adapter_status_special,
    "LoadUsedSpritesGFX": load_used_sprites_gfx,
    "LoadStandingSpritesGFX": load_standing_sprites_gfx,
    "LoadWalkingSpritesGFX": load_walking_sprites_gfx,
    "SetBitsForLinkTradeRequest": set_bits_for_link_trade_request,
    "SetBitsForBattleRequest": set_bits_for_battle_request,
    "SetBitsForTimeCapsuleRequest": set_bits_for_time_capsule_request,
    "AskMobileOrCable": ask_mobile_or_cable,
    "TryQuickSave": try_quick_save,
    "WaitForLinkedFriend": wait_for_linked_friend,
    "WaitForOtherPlayerToExit": wait_for_other_player_to_exit,
    "CableClubCheckWhichChris": cable_club_check_which_chris,
    "CheckBothSelectedSameRoom": check_both_selected_same_room,
    "CheckLinkTimeoutReceptionist": check_link_timeout_receptionist,
    "CheckLinkTimeout_Receptionist": check_link_timeout_receptionist,
    "CloseLink": close_link,
    "CheckTimeCapsuleCompatibility": check_time_capsule_compatibility,
    "EnterTimeCapsule": enter_time_capsule,
    "TimeCapsule": time_capsule,
    "MagnetTrain": magnet_train,
    "GiveOddEgg": give_odd_egg,
    "GiveParkBalls": give_park_balls,
    "SelectRandomBugContestContestants": select_random_bug_contest_contestants,
    "ContestDropOffMons": contest_drop_off_mons,
    "StartBugContestTimer": start_bug_contest_timer,
    "CheckBugContestTimer": check_bug_contest_timer,
    "BugContestJudging": bug_contest_judging,
    "BugContestSetCaughtContestMon": bug_contest_set_caught_contest_mon,
    "ChooseWildEncounterBugContest": choose_wild_encounter_bug_contest,
    "ContestReturnMons": contest_return_mons,
    "CheckPartyFullAfterContest": check_party_full_after_contest,
    "FailedLinkToPast": failed_link_to_past,
    "TradeCenter": trade_center,
    "Colosseum": colosseum,
    "BattleTowerAction": battle_tower_action,
    "CheckForBattleTowerRules": check_for_battle_tower_rules,
    "BattleTowerRoomMenu": battle_tower_room_menu,
    "BattleTowerMobileError": battle_tower_mobile_error,
    "BattleTowerBattle": battle_tower_battle,
    "BattleTowerFade": battle_tower_fade,
    "Menu_ChallengeExplanationCancel": menu_challenge_explanation_cancel,
    "GiveShuckle": give_shuckle,
    "ReturnShuckie": return_shuckie,
    "GiveDratini": give_dratini,
    "AskRememberPassword": ask_remember_password,
    "MoveDeletion": move_deletion,
    "BillsGrandfather": bills_grandfather,
    "DisplayCoinCaseBalance": display_coin_case_balance,
    "DisplayMoneyAndCoinBalance": display_money_and_coin_balance,
    "PlaceMoneyTopRight": place_money_top_right,
    "DisplayLinkRecord": display_link_record,
    "PrintTodaysLuckyNumber": print_todays_lucky_number,
    "CheckForLuckyNumberWinners": check_for_lucky_number_winners,
    "CheckLuckyNumberShowFlag": check_lucky_number_show_flag,
    "ResetLuckyNumberShowFlag": reset_lucky_number_show_flag,
    "NameRater": name_rater,
    "NameRival": name_rival,
    "OlderHaircutBrother": older_haircut_brother,
    "YoungerHaircutBrother": younger_haircut_brother,
    "DaisysGrooming": daisys_grooming,
    "ProfOaksPCBoot": prof_oaks_pc_boot,
    "PhotoStudio": photo_studio,
    "Diploma": diploma,
    "PrintDiploma": print_diploma,
    "TrainerHouse": trainer_house,
    "LoadOpponentTrainerAndPokemonWithOTSprite": load_opponent_trainer_and_pokemon_with_ot_sprite,
    "Function1700ba": function1700ba,
    "Function1011f1": function1011f1,
    "Function101220": function101220,
    "Function101225": function101225,
    "Function101231": function101231,
    "MoveTutor": move_tutor,
    "PokeSeer": poke_seer,
    "BuenasPassword": buenas_password,
    "BuenaPrize": buena_prize,
    "CelebiShrineEvent": celebi_shrine_event,
    "Mobile_SelectThreeMons": mobile_select_three_mons,
    "Function1037eb": function1037eb,
    "Function10383c": function10383c,
    "Function1037c2": function1037c2,
    "Function103780": function103780,
    "Function10387b": function10387b,
    "SnorlaxAwake": snorlax_awake,
    "StubbedTrainerRankings_Healings": stubbed_trainer_rankings_healings,
    "ToggleDecorationsVisibility": toggle_decorations_visibility,
    "ToggleMaptileDecorations": toggle_maptile_decorations,
    "FadeOutToWhite": fade_out_to_white,
    "FadeInFromWhite": fade_in_from_white,
    "FadeOutToBlack": fade_out_to_black,
    "FadeInFromBlack": fade_in_from_black,
    "Reset": reset_special,
} as Record<string, SpecialFunction>;
