import { z } from 'zod';
import {
  BugContestResultsSchema,
  BugContestStateSchema,
  BugContestTimerSchema,
  DayCareSchema,
  MoveSchema,
  PokemonSchema,
  RoamingPokemonSchema,
  TrainerSchema,
} from '../models';
import { LANDMARK_SPECIAL } from '../constants';
import { TEXTBOX_FAST_DELAY_FLAG } from '../text-constants';
import { DexMode } from '../enums/pokedex';
import { MonType } from '../enums/pokemon';
import { PrintOption } from '../enums/ui-enums';
import { MoveEffect, MoveName, PlayerGender, PokemonType } from '../enums';
import { ScriptMemorySchema } from './script-memory';

const NUM_POKEMON = 251;
const NUM_UNOWN = 26;

const defaultMove = {
    source_index: 1,
    name: MoveName.POUND,
    type: PokemonType.NORMAL,
    power: 40,
    accuracy: 100,
    pp: 35,
    effect: MoveEffect.NORMAL_HIT,
    effect_chance: 0,
};

const WildPokemonSchema = z
  .object({
    species: z.string().optional(),
    level: z.number().optional(),
  })
  .passthrough();

export const WRAMSchema = z.object({
  scene_name: z.string().default(''),
  event_flags: z.record(z.string(), z.boolean()).default({}),
  trainer_flags: z.record(z.string(), z.boolean()).default({}),
  battle_result: z.number().default(0),
  last_talked: z.number().default(0),
  pending_last_talked_position: z.tuple([z.number(), z.number()]).optional(),
  pending_last_talked_map: z.string().default(''),
  pending_last_talked_object: z.number().default(0),
  seen_trainer_distance: z.number().default(0),
  seen_trainer_direction: z.string().default(''),
  wRunningTrainerBattleScript: z.number().default(0),
  dont_restart_map_music: z.boolean().default(false),
  reload_map_after_battle: z.boolean().default(false),
  other_trainer_class: z.string().default(''),
  other_trainer_id: z.string().default(''),
  other_trainer: TrainerSchema.optional(),
  other_trainer_party: z.array(PokemonSchema).default([]),
  battle_type: z.string().default('BATTLETYPE_NORMAL'),
  safari_balls_remaining: z.number().default(0),
  safari_bait_remaining: z.number().default(0),
  safari_rocks_remaining: z.number().default(0),
  safari_time_remaining: z.number().default(0),
  safari_active: z.boolean().default(false),
  time_of_day: z.string().default('day'),
  current_map_group: z.number().default(0),
  current_map_id: z.number().default(0),
  wXCoord: z.number().default(0),
  wYCoord: z.number().default(0),
  player_x: z.number().default(0),
  player_y: z.number().default(0),
  player_subtile_x: z.number().default(0),
  player_subtile_y: z.number().default(0),
  player_palette_id: z.number().default(0),
  repel_steps: z.number().default(0),
  step_count: z.number().default(0),
  poison_step_count: z.number().default(0),
  happiness_step_count: z.number().default(0),
  wild_encounter_cooldown: z.number().default(0),
  wHeadbuttState: z.number().default(0),
  wHeadbuttCount: z.number().default(0),
  wHeadbuttLastStep: z.number().default(0),
  wTextDelayFrames: z.number().default(0),
  wTileAnimationTimer: z.number().default(0),
  wFrameCounter: z.number().default(0),
  wFrameCounter2: z.number().default(0),
  wSweetScentState: z.number().default(0),
  wSweetScentTarget: z.record(z.string(), z.union([z.number(), z.string()])).optional(),
  wSweetScentStepTimer: z.number().default(0),
  wCurSpriteOAMAddr: z.number().default(0),
  wBattleTextDelay: z.number().default(0),
  wBattleParticipantsNotFainted: z.number().default(0),
  wBattleParticipantsIncludingFainted: z.number().default(0),
  wBattleHasJustStarted: z.number().default(0),
  wBattleEnded: z.number().default(0),
  wPlayerMove: z.number().default(0),
  wEnemyMove: z.number().default(0),
  wNamedObjectIndex: z.number().default(0),
  wLastPlayerCounterMove: z.number().default(0),
  wLastEnemyCounterMove: z.number().default(0),
  wPlayerSubstituteHP: z.number().default(0),
  wEnemySubstituteHP: z.number().default(0),
  wBattleMonNick: z.array(z.number()).default(() => Array(11).fill(0)),
  wOTMonNick: z.array(z.number()).default(() => Array(11).fill(0)),
  wBattleMonOT: z.array(z.number()).default(() => Array(8).fill(0)),
  wOTMonOT: z.array(z.number()).default(() => Array(8).fill(0)),
  wPlayerStats: z
    .object({
      attack: z.number(),
      defense: z.number(),
      speed: z.number(),
      special_attack: z.number(),
      special_defense: z.number(),
    })
    .default({ attack: 0, defense: 0, speed: 0, special_attack: 0, special_defense: 0 }),
  wEnemyStats: z
    .object({
      attack: z.number(),
      defense: z.number(),
      speed: z.number(),
      special_attack: z.number(),
      special_defense: z.number(),
    })
    .default({ attack: 0, defense: 0, speed: 0, special_attack: 0, special_defense: 0 }),
  wPlayerMoveStruct: MoveSchema.default(defaultMove),
  wEnemyMoveStruct: MoveSchema.default(defaultMove),
  wInputType: z.number().default(0),
  wTextDelayFlags: z.number().default(0),
  wTextboxFlags: z.number().default(TEXTBOX_FAST_DELAY_FLAG),
  wOptions: z.number().default(0),
  wTextboxFrame: z.number().default(0),
  wGBPrinterBrightness: z.number().default(PrintOption.NORMAL),
  wOptions2: z.number().default(0),
  wFortuneTellerState: z.number().default(0),
  wFortuneTellerOutcome: z.number().default(0),
  wMapGroup: z.number().default(0),
  wMapNumber: z.number().default(0),
  wBTChoiceOfLvlGroup: z.number().default(0),
  wNrOfBeatenBattleTowerTrainers: z.number().default(0),
  wSpriteFlags: z.number().default(0),
  wPrevWarp: z.number().default(0),
  wPrevMapGroup: z.number().default(0),
  wPrevMapNumber: z.number().default(0),
  wBackupWarpNumber: z.number().default(0),
  wNextWarp: z.number().default(0),
  wNextMapGroup: z.number().default(0),
  wNextMapNumber: z.number().default(0),
  wCurLandmark: z.number().default(LANDMARK_SPECIAL),
  wPrevLandmark: z.number().default(LANDMARK_SPECIAL),
  wLandmarkSignTimer: z.number().default(0),
  wMapNameSignFlags: z.number().default(0),
  wMapEventStatus: z.number().default(0),
  wEnabledPlayerEvents: z.number().default(255),
  wBackupMapGroup: z.number().default(0),
  wBackupMapNumber: z.number().default(0),
  wLastSpawnMapGroup: z.number().default(0),
  wLastSpawnMapNumber: z.number().default(0),
  wDefaultSpawnpoint: z.number().default(0),
  // ASM: pokecrystal_disassembly/ram/wram.asm::wSpawnAfterChampion.
  wSpawnAfterChampion: z.number().default(0),
  wEscapeRopeOrDigType: z.number().default(0),
  wDigWarpNumber: z.number().default(0),
  wDigMapGroup: z.number().default(0),
  wDigMapNumber: z.number().default(0),
  last_pokecenter_map_name: z.string().default(''),
  last_pokecenter_map_group: z.number().default(0),
  last_pokecenter_map_number: z.number().default(0),
  last_pokecenter_player_x: z.number().default(0),
  last_pokecenter_player_y: z.number().default(0),
  last_pokecenter_backup_map_group: z.number().default(0),
  last_pokecenter_backup_map_number: z.number().default(0),
  last_pokecenter_coordinate_units: z.string().default('block'),
  wild_pokemon: WildPokemonSchema.default({}),
  wMomsName: z.string().default(''),
  wDudeItems: z.record(z.string(), z.number()).default({}),
  wDudeKeyItems: z.record(z.string(), z.number()).default({}),
  wDudeBalls: z.record(z.string(), z.number()).default({}),
  // ASM: pokecrystal_disassembly/ram/wram.asm::wWhichRegisteredItem / wRegisteredItem
  wWhichRegisteredItem: z.number().default(0),
  wRegisteredItem: z.string().default(""),
  // ASM: wRoamMon1-3 are fixed WRAM slots even before InitRoamMons runs.
  roaming_pokemon: z
    .array(RoamingPokemonSchema)
    .default(() => Array.from({ length: 3 }, () => RoamingPokemonSchema.parse({}))),
  player_gender: z.nativeEnum(PlayerGender).default(PlayerGender.MALE),
  wPlayerState: z.number().default(0),
  wPlayerGender: z.number().default(0),
  // ASM: pokecrystal_disassembly/ram/wram.asm::wHallOfFameCount
  wHallOfFameCount: z.number().default(0),
  map_scenes: z.record(z.string(), z.string()).default({}),
  map_scene_indices: z.record(z.string(), z.number()).default({}),
  map_scene_order: z.record(z.string(), z.array(z.string())).default({}),
  map_scene_state: z.record(z.string(), z.union([z.string(), z.number()])).default({}),
  engine_flags: z.record(z.string(), z.boolean()).default({}),
  // ASM: pokecrystal_disassembly/ram/wram.asm::wBikeFlags (strength, always-on-bike, downhill).
  wBikeFlags: z.number().default(0),
  variable_sprites: z.record(z.string(), z.string()).default({}),
  decorations_visible: z.boolean().default(false),
  maptile_decorations_visible: z.boolean().default(false),
  wDecoBed: z.number().default(0x02), // Defaults to DECO_FEATHERY_BED
  wDecoPlant: z.number().default(0x00),
  wDecoPoster: z.number().default(0x10), // Defaults to DECO_TOWN_MAP
  wDecoCarpet: z.number().default(0x00),
  wDecoConsole: z.number().default(0x00),
  wDecoLeftOrnament: z.number().default(0x00),
  wDecoRightOrnament: z.number().default(0x00),
  wDecoBigDoll: z.number().default(0x00),
  wMapMusic: z.string().default(""),
  lucky_number_show_flag: z.boolean().default(false),
  trainer_rankings_healings: z.number().default(0),
  // ASM: pokecrystal_disassembly/engine/events/overworld.asm::GetSurfType stores PLAYER_SURF/_PIKA here.
  wSurfingPlayerState: z.number().default(0),
  // ASM: pokecrystal_disassembly/engine/events/overworld.asm::TryWhirlpoolMenu stores cut/whirlpool replacement metadata here.
  wCutWhirlpoolOverworldBlockAddr: z.tuple([z.number(), z.number()]).optional(),
  wCutWhirlpoolReplacementBlock: z.number().default(0),
  wCutWhirlpoolAnimationType: z.number().default(0),
  // ASM: pokecrystal_disassembly/engine/events/overworld.asm::SetStrengthFlag writes the acting species for cry playback.
  wStrengthSpecies: z.string().default(""),
  surfing: z.boolean().default(false),
  flash_active_maps: z.record(z.string(), z.boolean()).default({}),
  scheduled_phone_calls: z.array(z.string()).default([]),
  bug_contest_state: BugContestStateSchema.default(() => BugContestStateSchema.parse({})),
  bug_contest_results: BugContestResultsSchema.default(() => BugContestResultsSchema.parse({})),
  bug_contest_timer: BugContestTimerSchema.default(() => BugContestTimerSchema.parse({})),
  bug_contest_second_party_species: z.string().default(''),
  bug_contest_caught_mon: PokemonSchema.optional(),
  start_menu_cursor: z.number().default(0),
  wTMHMPocketCursor: z.number().default(0),
  wTMHMPocketScrollPosition: z.number().default(0),
  day_care: DayCareSchema.default(() => DayCareSchema.parse({})),
  pokegear_card: z.number().default(0),
  pokegear_map_cursor_landmark: z.number().default(0),
  pokegear_phone_cursor_position: z.number().default(0),
  pokegear_phone_scroll_position: z.number().default(0),
  pokegear_radio_frequency_raw: z.number().default(0),
  pokegear_map_player_landmark: z.number().default(0),
  pokegear_map_region: z.string().default('JOHTO'),
  wCurDay: z.number().default(0),
  blue_card_balance: z.number().default(0),
  buenas_password_category: z.number().default(0),
  buenas_password_index: z.number().default(0),
  buenas_password_generation_day: z.number().default(-1),
  wKenjiBreakTimer: z.number().default(0),
  daily_reset_timer: z.number().default(0),
  daily_flags1: z.number().default(0),
  daily_flags2: z.number().default(0),
  swarm_flags: z.number().default(0),
  daily_rematch_flags: z.array(z.number()).default(() => [0, 0, 0, 0]),
  daily_phone_item_flags: z.array(z.number()).default(() => [0, 0, 0, 0]),
  daily_phone_time_of_day_flags: z.array(z.number()).default(() => [0, 0, 0, 0]),
  wFishingSwarmFlag: z.number().default(0),
  wFishingRodState: z.number().default(0),
  wFishingRodRod: z.number().default(0),
  wFishingRodBites: z.number().default(0),
  wFishingResult: z.number().default(0),
  wYanmaMapGroup: z.number().default(0),
  wYanmaMapNumber: z.number().default(0),
  wDunsparceMapGroup: z.number().default(0),
  wDunsparceMapNumber: z.number().default(0),
  roam_mons_current_map_group: z.number().default(-1),
  roam_mons_current_map_number: z.number().default(-1),
  roam_mons_last_map_group: z.number().default(-1),
  roam_mons_last_map_number: z.number().default(-1),
  wRockSmashState: z.number().default(0),
  wRockSmashTile: z.tuple([z.number(), z.number()]).optional(),
  wRockSmashEncounter: z.record(z.string(), z.union([z.number(), z.string()])).optional(),
  wRockSmashStepTimer: z.number().default(0),
  wPartyMenuCursor: z.number().default(0),
  wPartyMenuActionText: z.number().default(0),
  wPartyCount: z.number().default(0),
  wCurPartyMon: z.number().default(0),
  wCurPartySpecies: z.string().default(''),
  wCurBattleMon: z.number().default(0),
  wSwitchMon: z.number().default(0),
  wLastPlayerMon: z.number().default(0),
  wTempBattleMonSpecies: z.string().default(''),
  wMonType: z.nativeEnum(MonType).default(MonType.PARTYMON),
  wTempMon: PokemonSchema.optional(),
  wMonSubmenuCount: z.number().default(0),
  wMonSubmenuItems: z.array(z.number()).default(() => Array(9).fill(0)),
  wMenuBorderTopCoord: z.number().default(0),
  wMenuBorderBottomCoord: z.number().default(0),
  wMenuCursorY: z.number().default(0),
  w2DMenuNumRows: z.number().default(0),
  wMenuJoypadFilter: z.number().default(0),
  wMenuJoypad: z.number().default(0),
  wMenuSelection: z.number().default(0),
  wMenuDataFlags: z.number().default(0),
  wMenuDataItems: z.number().default(0),
  wStatsScreenFlags: z.number().default(0),
  wMoveDeleterState: z.number().default(0),
  wMoveDeleterMon: z.number().default(0),
  wMoveDeleterSlot: z.number().default(0),
  wLinkMode: z.number().default(0),
  wPlayerLinkAction: z.number().default(0),
  wChosenCableClubRoom: z.number().default(0),
  menu_sprite_anims_enabled: z.boolean().default(false),
  wBillsPC_LoadedBox: z.number().default(0),
  wBillsPC_CursorPosition: z.number().default(0),
  wBillsPC_ScrollPosition: z.number().default(0),
  wBillsPC_NumMonsOnScreen: z.number().default(0),
  wBillsPC_NumMonsInBox: z.number().default(0),
  wPokedexOrder: z.array(z.number()).default(() => Array(NUM_POKEMON).fill(0)),
  wDexListingScrollOffset: z.number().default(0),
  wDexListingCursor: z.number().default(0),
  wDexListingEnd: z.number().default(NUM_POKEMON),
  wDexListingHeight: z.number().default(7),
  wCurDexMode: z.nativeEnum(DexMode).default(DexMode.NEW),
  wLastDexMode: z.nativeEnum(DexMode).default(DexMode.NEW),
  wDexArrowCursorPosIndex: z.number().default(0),
  wDexListingScrollOffsetBackup: z.number().default(0),
  wDexListingCursorBackup: z.number().default(0),
  wPrevDexEntry: z.number().default(0),
  wUnlockedUnownMode: z.boolean().default(false),
  wUnownDex: z.array(z.number()).default(() => Array(NUM_UNOWN).fill(0)),
  wUnownLetter: z.number().default(0),
  wUnownState: z.number().default(0),
  wSolvedUnownPuzzle: z.boolean().default(false),
  wUnownLetterIndex: z.number().default(0),
  wDexSearchMonType1: z.number().default(0),
  wDexSearchMonType2: z.number().default(0),
  wDexSearchResultCount: z.number().default(0),
  wDexSearchSlowpokeFrame: z.number().default(0),
  wDexArrowCursorDelayCounter: z.number().default(0),
  wDexArrowCursorBlinkCounter: z.number().default(0),
  wDexCurUnownIndex: z.number().default(0),
  wDexUnownCount: z.number().default(0),
  wDexConvertedMonType: z.number().default(0),
  wDexCurLocation: z.number().default(0),
  wJumptableIndex: z.number().default(0),
  wPrevDexEntryJumptableIndex: z.number().default(0),
  wPrevDexEntryBackup: z.number().default(0),
  wCurHPPal: z.number().default(0),
  wHPPals: z.array(z.number()).default(() => Array(6).fill(0)),
  wSGBPals: z.number().default(0),
  script_memory: ScriptMemorySchema,
  wMagikarpLengthFeet: z.number().default(0),
  wMagikarpLengthInches: z.number().default(0),
  wBestMagikarpLengthFeet: z.number().default(0),
  wBestMagikarpLengthInches: z.number().default(0),
  best_magikarp_owner_name: z.string().default(''),
  instant_mode: z.boolean().default(false),
});

export type WRAM = z.infer<typeof WRAMSchema>;
